version: '2'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=neil820724
      - POSTGRES_DB=homeworknode

  adminer:
    image: adminer
    ports:
      - "8080:8080"